spring:
  application:
    name: recours
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/padweb
    username: postgres
    password: postgres
  sql:
    init:
      platform: postgres
      mode: always
